name: Flutter CI-CD

on:
  push:
    branches: [ "main","dev" ]

jobs:
  build:
    if: "(contains(github.event.head_commit.message, 'merge') || contains(github.event.head_commit.message, 'Merge') || contains(github.event.head_commit.message, 'MERGE') || startsWith(github.event.head_commit.message, 'Merge')) == false"
    runs-on: ubuntu-latest

    outputs:
      appVersion: ${{ steps.get-app-version.outputs.appVersion }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.pub-cache
            ~/flutter/.pub-cache
            ~/android/.gradle/caches
            ~/android/.gradle/wrapper
          key: ${{ runner.os }}-pub-gradle-${{ hashFiles('**/*.yaml') }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          # flutter-version: '3.16.x'
          channel: "stable"

      - name: Install dependencies
        run: dart pub get

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      # - name: Analyze project source
      #   run: dart analyze

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      # - name: Run tests
      #   run: dart test

      - name: Generate constants file
        run: |
          echo "class ApiConstants {" >> lib/data/constants/constants.dart
          if [[ $GITHUB_REF == refs/heads/main ]]; then
            echo MAIN BRANCH
            echo "static const String baseAuthUrl = '${{ secrets.PROD_AUTH_URL }}';" >> lib/data/constants/constants.dart
          else
            echo DEV BRANCH
            echo "static const String baseAuthUrl = '${{ secrets.DEV_AUTH_URL }}';" >> lib/data/constants/constants.dart
          fi
          echo "}" >> lib/data/constants/constants.dart

      - name: Get app version
        id: get-app-version
        run: |
          APP_VERSION=$(grep -oP 'version: \K(.+)' pubspec.yaml)
          echo "App Version: $APP_VERSION"
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
          echo "appVersion=$APP_VERSION" >> $GITHUB_OUTPUT

      - name: Build APK
        run: flutter build apk --release

      - name: Rename APK
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/seymo.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/seymo.apk

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download APKs
        uses: actions/download-artifact@v4
        env:
          appVersion: ${{ needs.build.outputs.appVersion }}
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/

      - name: Create Release and Upload APK to Release
        id: create_and_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_REPOSITORY: my_gh_org/my_gh_repo
          appVersion: ${{ needs.build.outputs.appVersion }}
        with:
          files: build/app/outputs/flutter-apk/seymo.apk
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release v${{ env.appVersion }}
          tag_name: v${{ env.appVersion }}
          draft: false
          prerelease: false

      - name: Get release information
        id: release_info
        run: |
          release_data=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/HumanDevIP/Pay-FrontEnd-MobileApp/releases/latest")
          download_url=$(echo "$release_data" | jq -r '.assets[0].browser_download_url')
          echo "Download URL: $download_url"